### ISSUE TITLE
Репозитории

### ISSUE THREAD

**Issue by oldSorcerer** [ThierryGuetta/JavaRushTasks#1]
у тебя может быть сколько угодно открытых репозиториев. 
мой совет выдели следующий код [JavaRushTasks](https://github.com/ThierryGuetta/JavaRushTasks)/[1.JavaSyntax](https://github.com/ThierryGuetta/JavaRushTasks/tree/master/1.JavaSyntax)/[src](https://github.com/ThierryGuetta/JavaRushTasks/tree/master/1.JavaSyntax/src)/MyTests/ из проекта  [JavaRushTasks](https://github.com/ThierryGuetta/JavaRushTasks) в отдельный репозиторий что-то вроде мои тест файлы или мои примеры работы массивами
1 идея 1 репозиторий не нужно все смешивать

**Comment by ThierryGuetta** [comment]
Привет. Хорошо, исправлю!
